#%RAML 1.0
title: HandyNote Service
baseUri: http://localhost:3000/api
version: v1.0
mediaType: application/json

/notes:
  displayName: Notes
  description: API for manage notes
  get:
    description: |
      Get all notes belongs to the user associated with either provided token(from header "X-Auth-Token") or logged in session
    responses:
      200:
        body:
          example: |
            array of notes, refer to DB schema -> notes
  post:
    description: Add a note
    body:
      example: |
        refer to DB schema -> notes
    responses:
      201:
        body:
          example: |
            refer to DB schema -> notes
  /{id}:
    uriParameters:
      id:
        example: a48c3779-eb14-4697-a490-eeb0125196f4
    delete:
      description: Delete a note
      responses:
        204:
          body:
            example:  |
              refer to DB schema -> notes
