#%RAML 1.0
title: HandyNote Service
baseUri: http://localhost:3000/api
version: v1.0
mediaType: application/json

/notes:
  displayName: Notes
  description: API for manage notes
  get:
    description: |
      Get all notes belongs to the user associated with either provided token(from header "X-Auth-Token") or logged in session
    responses:
      200:
        body:
          example: |
            array of notes, refer to DB schema -> Notes
  post:
    description: Add a note
    body:
      example: |
        refer to DB schema -> Notes
    responses:
      201:
        body:
          example: |
            {
              result: "success",
              note_id: "f9131869-895b-47f0-ba2b-e15ca8a5be06"
            }
            {
              result: "fail",
              fault": "xxx" // some reason
            }
